import java.io.File
import java.util.Properties

/**
 * Ensures mobile/local.properties exists so AGP can find the Android SDK on fresh
 * clones without requiring a manual ANDROID_HOME export.
 *
 * Resolution order:
 * 1. Existing local.properties sdk.dir (leave untouched when valid)
 * 2. ANDROID_HOME / ANDROID_SDK_ROOT
 * 3. Default install locations (macOS / Linux)
 *
 * If nothing is found, leave local.properties alone and let AGP fail with its
 * usual message — we only fix the "SDK is installed but Gradle can't see it" case.
 */
val localPropertiesFile = File(rootDir, "local.properties")
val existingSdkValid = if (localPropertiesFile.isFile) {
    val existing = Properties().apply {
        localPropertiesFile.inputStream().use { load(it) }
    }
    val sdkDir = existing.getProperty("sdk.dir")?.takeIf { it.isNotBlank() }
    sdkDir != null && File(sdkDir).isDirectory
} else {
    false
}

if (!existingSdkValid) {
    val fromEnv = sequenceOf("ANDROID_HOME", "ANDROID_SDK_ROOT")
        .mapNotNull { System.getenv(it)?.takeIf(String::isNotBlank) }
        .map(::File)
        .firstOrNull { it.isDirectory }

    val home = File(System.getProperty("user.home"))
    val fromDefault = sequenceOf(
        File(home, "Library/Android/sdk"), // macOS (Android Studio default)
        File(home, "Android/Sdk"), // Linux
    ).firstOrNull { it.isDirectory }

    val sdk = fromEnv ?: fromDefault
    if (sdk != null) {
        // Forward slashes work on Windows and macOS/Linux for AGP's sdk.dir.
        val sdkPath = sdk.canonicalPath.replace('\\', '/')
        localPropertiesFile.writeText(
            "# Generated by gradle/androidSdkBootstrap.settings.gradle.kts — do not commit\n" +
                "sdk.dir=$sdkPath\n",
        )
        println("Generated ${localPropertiesFile.name} with sdk.dir=$sdkPath")
    }
}
